name: Deploy .NET Backend simple

on:
  workflow_dispatch: # Allow manual triggering from GitHub UI
  push:
    branches:
      - main
    paths:
      - "Backend/**"

# Environment variables used throughout the workflow
env:
  AZURE_WEBAPP_NAME: hackernews-backend
  AZURE_WEBAPP_PACKAGE_PATH: ".Backend/HackerNews.Api/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "Backend/HackerNews.Api.sln"
  API_PROJECT_PATH: "Backend/HackerNews.Api"
  PUBLISH_DIR: "./publish"

jobs:
  build-and-deploy:
    name: Deploy .NET Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Restore Dependencies
        run: dotnet restore Backend/HackerNews.Api

      - name: Build and Publish
        run: |
          dotnet publish Backend/HackerNews.Api -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: hackernews-backend
          package: ./publish
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
